// Generated by tools/build_works.py — do not edit by hand.
const WORKS_DATA = [
    {
        num: 4,
        title: "Arm Materializer",
        subtitle: "Dynamic Pseudo-Attraction for Modulating Perceived Arm Material",
        year: "2026",
        imagePaths: [
            "works/img/work4/main-image.jpg",
            "works/img/work4/algorithm.jpg",
            "works/img/work4/system-architecture.jpg"
        ],
        detailsPath: "works/work4-details.html"
    },
    {
        num: 3,
        title: "Semantic See-through Goggles",
        subtitle: "Linguistic Virtual Reality in (Artificial) Intelligence",
        year: "2024",
        imagePaths: [
            "works/img/work3/teaser.jpg",
            "works/img/work3/still.jpg",
            "works/img/work3/workshop1.jpg",
            "works/img/work3/workshop2.jpg"
        ],
        detailsPath: "works/work3-details.html"
    },
    {
        num: 2,
        title: "ForceField",
        subtitle: "Visualizing Intermaterial Interaction",
        year: "2023",
        imagePaths: [
            "works/img/work2/systemimage2.jpg",
            "works/img/work2/poster.jpg",
            "works/img/work2/systemimage3.jpg",
            "works/img/work2/systemoverview.png"
        ],
        detailsPath: "works/work2-details.html"
    },
    {
        num: 1,
        title: "The Legend of Holy Sword",
        subtitle: "Proof of Concentration",
        year: "2023",
        imagePaths: [
            "works/img/work1/teaser-new.jpg",
            "works/img/work1/seed-stage.jpg",
            "works/img/work1/09338401.jpg",
            "works/img/work1/12a801fb.jpg"
        ],
        detailsPath: "works/work1-details.html"
    }
];
