// Generated by tools/build_works.py — do not edit by hand.
const WORKS_DATA = [
    {
        num: 4,
        title: "Arm Materializer",
        subtitle: "Dynamic Pseudo-Attraction for Modulating Perceived Arm Material",
        year: "2026",
        imagePath: "works/img/work4/main-image.jpg",
        detailsPath: "works/work4-details.html"
    },
    {
        num: 3,
        title: "Semantic See-through Goggles",
        subtitle: "Linguistic Virtual Reality in (Artificial) Intelligence",
        year: "2024",
        imagePath: "works/img/work3/teaser.jpg",
        detailsPath: "works/work3-details.html"
    },
    {
        num: 2,
        title: "ForceField",
        subtitle: "Visualizing Intermaterial Interaction",
        year: "2023",
        imagePath: "works/img/work2/systemimage2.jpg",
        detailsPath: "works/work2-details.html"
    },
    {
        num: 1,
        title: "The Legend of Holy Sword",
        subtitle: "Proof of Concentration",
        year: "2023",
        imagePath: "works/img/work1/teaser-new.jpg",
        detailsPath: "works/work1-details.html"
    }
];
